services:
  # フロントエンド：Next.js
  blog_frontend:
    image: node:23.10-bullseye
    container_name: frontend_next_container
    environment:
      - TZ=Asia/Tokyo
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "yarn install && yarn dev"

  # バックエンド：Django
  blog_backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend_django_container
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 8000:8000
    tty: true
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
