services:
  # フロントエンド：Next.js
  blog-frontend:
    image: node:23.10-bullseye
    container_name: frontend_next_container
    environment:
      - TZ=Asia/Tokyo
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "yarn install && yarn dev"

  # バックエンド：Django
  blog-backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend_django_container
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    networks:
      - backend_network
    tty: true
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000

  # オブジェクトストレージ：MinIO
  blog-storage:
    image: minio/minio:RELEASE.2025-04-08T15-41-24Z
    container_name: minio_container
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - backend_network
    tty: true
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopassword
    volumes:
      - minio-volume:/data
    command: server /data --console-address :9001

# ボリュームの設定
volumes:
  minio-volume:

# ネットワークの設定
networks:
  backend_network:
    driver: bridge