# Generated by Django 5.1.7 on 2025-04-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='titlr',
            new_name='title',
        ),
    ]
