# Generated by Django 5.2 on 2025-04-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='画像タイトル')),
                ('thumbnail_url', models.CharField(max_length=256, verbose_name='サムネイル画像の URL')),
                ('display_url', models.CharField(max_length=256, verbose_name='表示用画像の URL')),
                ('original_url', models.CharField(max_length=256, verbose_name='オリジナル画像の URL')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
            ],
        ),
    ]
